package com.groupdocs.ui.viewer.spring.common.util;

import org.apache.commons.lang3.builder.ToStringBuilder;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * Data was taken from https://www.freeformatter.com/mime-types-list.html
 */
public enum MediaTypes {
    _3D_CROSSWORD_PLUGIN("3D Crossword Plugin", "application/vnd.hzn-3d-crossword", ".x3d"),
    _3GP("3GP", "video/3gpp", ".3gp"),
    _3GP2("3GP2", "video/3gpp2", ".3g2"),
    _3GPP_MSEQ_FILE("3GPP MSEQ File", "application/vnd.mseq", ".mseq"),
    _3M_POST_IT_NOTES("3M Post It Notes", "application/vnd.3m.post-it-notes", ".pwn"),
    _3RD_GENERATION_PARTNERSHIP_PROJECT_PIC_LARGE("3rd Generation Partnership Project - Pic Large", "application/vnd.3gpp.pic-bw-large", ".plb"),
    _3RD_GENERATION_PARTNERSHIP_PROJECT_PIC_SMALL("3rd Generation Partnership Project - Pic Small", "application/vnd.3gpp.pic-bw-small", ".psb"),
    _3RD_GENERATION_PARTNERSHIP_PROJECT_PIC_VAR("3rd Generation Partnership Project - Pic Var", "application/vnd.3gpp.pic-bw-var", ".pvb"),
    _3RD_GENERATION_PARTNERSHIP_PROJECT_TRANSACTION_CAPABILITIES_APPLICATION_PART("3rd Generation Partnership Project - Transaction Capabilities Application Part", "application/vnd.3gpp2.tcap", ".tcap"),
    _7_ZIP("7-Zip", "application/x-7z-compressed", ".7z"),
    ABIWORD("AbiWord", "application/x-abiword", ".abw"),
    ACE_ARCHIVE("Ace Archive", "application/x-ace-compressed", ".ace"),
    ACTIVE_CONTENT_COMPRESSION("Active Content Compression", "application/vnd.americandynamics.acc", ".acc"),
    ACU_COBOL("ACU Cobol", "application/vnd.acucobol", ".acu"),
    ACU_COBOL_CORP("ACU Cobol", "application/vnd.acucorp", ".atc"),
    ADAPTIVE_DIFFERENTIAL_PULSE_CODE_MODULATION("Adaptive differential pulse-code modulation", "audio/adpcm", ".adp"),
    ADOBE_MACROPEDIA_AUTHORWARE_BINARY_FILE("Adobe (Macropedia) Authorware - Binary File", "application/x-authorware-bin", ".aab"),
    ADOBE_MACROPEDIA_AUTHORWARE_MAP("Adobe (Macropedia) Authorware - Map", "application/x-authorware-map", ".aam"),
    ADOBE_MACROPEDIA_AUTHORWARE_SEGMENT_FILE("Adobe (Macropedia) Authorware - Segment File", "application/x-authorware-seg", ".aas"),
    ADOBE_AIR_APPLICATION("Adobe AIR Application", "application/vnd.adobe.air-application-installer-package+zip", ".air"),
    ADOBE_FLASH("Adobe Flash", "application/x-shockwave-flash", ".swf"),
    ADOBE_FLEX_PROJECT("Adobe Flex Project", "application/vnd.adobe.fxp", ".fxp"),
    ADOBE_PORTABLE_DOCUMENT_FORMAT("Adobe Portable Document Format", "application/pdf", ".pdf"),
    ADOBE_POSTSCRIPT_PRINTER_DESCRIPTION_FILE_FORMAT("Adobe PostScript Printer Description File Format", "application/vnd.cups-ppd", ".ppd"),
    ADOBE_SHOCKWAVE_PLAYER("Adobe Shockwave Player", "application/x-director", ".dir"),
    ADOBE_XML_DATA_PACKAGE("Adobe XML Data Package", "application/vnd.adobe.xdp+xml", ".xdp"),
    ADOBE_XML_FORMS_DATA_FORMAT("Adobe XML Forms Data Format", "application/vnd.adobe.xfdf", ".xfdf"),
    ADVANCED_AUDIO_CODING_AAC("Advanced Audio Coding (AAC)", "audio/x-aac", ".aac"),
    AHEAD_AIR_APPLICATION("Ahead AIR Application", "application/vnd.ahead.space", ".ahead"),
    AIRZIP_FILESECURE_ASF("AirZip FileSECURE", "application/vnd.airzip.filesecure.azf", ".azf"),
    AIRZIP_FILESECURE_AZS("AirZip FileSECURE", "application/vnd.airzip.filesecure.azs", ".azs"),
    AMAZON_KINDLE_EBOOK_FORMAT("Amazon Kindle eBook format", "application/vnd.amazon.ebook", ".azw"),
    AMIGADE("AmigaDE", "application/vnd.amiga.ami", ".ami"),
    ANDREW_TOOLKIT("Andrew Toolkit", "application/andrew-inset", null),
    ANDROID_PACKAGE_ARCHIVE("Android Package Archive", "application/vnd.android.package-archive", ".apk"),
    ANSER_WEB_TERMINAL_CLIENT_CERTIFICATE_ISSUE("ANSER-WEB Terminal Client - Certificate Issue", "application/vnd.anser-web-certificate-issue-initiation", ".cii"),
    ANSER_WEB_TERMINAL_CLIENT_WEB_FUNDS_TRANSFER("ANSER-WEB Terminal Client - Web Funds Transfer", "application/vnd.anser-web-funds-transfer-initiation", ".fti"),
    ANTIX_GAME_PLAYER("Antix Game Player", "application/vnd.antix.game-component", ".atx"),
    APPLE_DISK_IMAGE("Apple Disk Image", "application/x-apple-diskimage", ".dmg"),
    APPLE_INSTALLER_PACKAGE("Apple Installer Package", "application/vnd.apple.installer+xml", ".mpkg"),
    APPLIXWARE("Applixware", "application/applixware", ".aw"),
    ARCHIPELAGO_LESSON_PLAYER("Archipelago Lesson Player", "application/vnd.hhe.lesson-player", ".les"),
    ARISTA_NETWORKS_SOFTWARE_IMAGE("Arista Networks Software Image", "application/vnd.aristanetworks.swi", ".swi"),
    ASSEMBLER_SOURCE_FILE("Assembler Source File", "text/x-asm", ".s"),
    ATOM_PUBLISHING_PROTOCOL("Atom Publishing Protocol", "application/atomcat+xml", ".atomcat"),
    ATOM_PUBLISHING_PROTOCOL_SERVICE_DOCUMENT("Atom Publishing Protocol Service Document", "application/atomsvc+xml", ".atomsvc"),
    ATOM_SYNDICATION_FORMAT_ATOM("Atom Syndication Format", "application/atom+xml", ".atom,"),
    ATOM_SYNDICATION_FORMAT_XML("Atom Syndication Format", "application/atom+xml", ".xml"),
    ATTRIBUTE_CERTIFICATE("Attribute Certificate", "application/pkix-attr-cert", ".ac"),
    AUDIO_INTERCHANGE_FILE_FORMAT("Audio Interchange File Format", "audio/x-aiff", ".aif"),
    AUDIO_VIDEO_INTERLEAVE_AVI("Audio Video Interleave (AVI)", "video/x-msvideo", ".avi"),
    AUDIOGRAPH("Audiograph", "application/vnd.audiograph", ".aep"),
    AUTOCAD_DXF("AutoCAD DXF", "image/vnd.dxf", ".dxf"),
    AUTODESK_DESIGN_WEB_FORMAT_DWF("Autodesk Design Web Format (DWF)", "model/vnd.dwf", ".dwf"),
    BAS_PARTITUR_FORMAT("BAS Partitur Format", "text/plain-bas", ".par"),
    BINARY_CPIO_ARCHIVE("Binary CPIO Archive", "application/x-bcpio", ".bcpio"),
    BINARY_DATA("Binary Data", "application/octet-stream", ".bin"),
    BITMAP_IMAGE_FILE("Bitmap Image File", "image/bmp", ".bmp"),
    BITTORRENT("BitTorrent", "application/x-bittorrent", ".torrent"),
    BLACKBERRY_COD_FILE("Blackberry COD File", "application/vnd.rim.cod", ".cod"),
    BLUEICE_RESEARCH_MULTIPASS("Blueice Research Multipass", "application/vnd.blueice.multipass", ".mpm"),
    BMI_DRAWING_DATA_INTERCHANGE("BMI Drawing Data Interchange", "application/vnd.bmi", ".bmi"),
    BOURNE_SHELL_SCRIPT("Bourne Shell Script", "application/x-sh", ".sh"),
    BTIF("BTIF", "image/prs.btif", ".btif"),
    BUSINESSOBJECTS("BusinessObjects", "application/vnd.businessobjects", ".rep"),
    BZIP_ARCHIVE("Bzip Archive", "application/x-bzip", ".bz"),
    BZIP2_ARCHIVE("Bzip2 Archive", "application/x-bzip2", ".bz2"),
    C_SHELL_SCRIPT("C Shell Script", "application/x-csh", ".csh"),
    C_SOURCE_FILE("C Source File", "text/x-c", ".c"),
    CAMBRIDGESOFT_CHEM_DRAW("CambridgeSoft Chem Draw", "application/vnd.chemdraw+xml", ".cdxml"),
    CASCADING_STYLE_SHEETS_CSS("Cascading Style Sheets (CSS)", "text/css", ".css"),
    CHEMDRAW_EXCHANGE_FILE("ChemDraw eXchange file", "chemical/x-cdx", ".cdx"),
    CHEMICAL_MARKUP_LANGUAGE("Chemical Markup Language", "chemical/x-cml", ".cml"),
    CHEMICAL_STYLE_MARKUP_LANGUAGE("Chemical Style Markup Language", "chemical/x-csml", ".csml"),
    CIM_DATABASE("CIM Database", "application/vnd.contact.cmsg", ".cdbcmsg"),
    CLAYMORE_DATA_FILES("Claymore Data Files", "application/vnd.claymore", ".cla"),
    CLONK_GAME("Clonk Game", "application/vnd.clonk.c4group", ".c4g"),
    CLOSE_CAPTIONING_SUBTITLE("Close Captioning - Subtitle", "image/vnd.dvb.subtitle", ".sub"),
    CLOUD_DATA_MANAGEMENT_INTERFACE_CDMI_CAPABILITY("Cloud Data Management Interface (CDMI) - Capability", "application/cdmi-capability", ".cdmia"),
    CLOUD_DATA_MANAGEMENT_INTERFACE_CDMI_CONTAIMER("Cloud Data Management Interface (CDMI) - Contaimer", "application/cdmi-container", ".cdmic"),
    CLOUD_DATA_MANAGEMENT_INTERFACE_CDMI_DOMAIN("Cloud Data Management Interface (CDMI) - Domain", "application/cdmi-domain", ".cdmid"),
    CLOUD_DATA_MANAGEMENT_INTERFACE_CDMI_OBJECT("Cloud Data Management Interface (CDMI) - Object", "application/cdmi-object", ".cdmio"),
    CLOUD_DATA_MANAGEMENT_INTERFACE_CDMI_QUEUE("Cloud Data Management Interface (CDMI) - Queue", "application/cdmi-queue", ".cdmiq"),
    CLUETRUST_CARTOMOBILE_CONFIG("ClueTrust CartoMobile - Config", "application/vnd.cluetrust.cartomobile-config", ".c11amc"),
    CLUETRUST_CARTOMOBILE_CONFIG_PACKAGE("ClueTrust CartoMobile - Config Package", "application/vnd.cluetrust.cartomobile-config-pkg", ".c11amz"),
    CMU_IMAGE("CMU Image", "image/x-cmu-raster", ".ras"),
    COLLADA("COLLADA", "model/vnd.collada+xml", ".dae"),
    COMMA_SEPERATED_VALUES("Comma-Seperated Values", "text/csv", ".csv"),
    COMPACT_PRO("Compact Pro", "application/mac-compactpro", ".cpt"),
    COMPILED_WIRELESS_MARKUP_LANGUAGE_WMLC("Compiled Wireless Markup Language (WMLC)", "application/vnd.wap.wmlc", ".wmlc"),
    COMPUTER_GRAPHICS_METAFILE("Computer Graphics Metafile", "image/cgm", ".cgm"),
    COOLTALK("CoolTalk", "x-conference/x-cooltalk", ".ice"),
    COREL_METAFILE_EXCHANGE_CMX("Corel Metafile Exchange (CMX)", "image/x-cmx", ".cmx"),
    CORELXARA("CorelXARA", "application/vnd.xara", ".xar"),
    COSMOCALLER("CosmoCaller", "application/vnd.cosmocaller", ".cmc"),
    CPIO_ARCHIVE("CPIO Archive", "application/x-cpio", ".cpio"),
    CRICKSOFTWARE_CLICKER("CrickSoftware - Clicker", "application/vnd.crick.clicker", ".clkx"),
    CRICKSOFTWARE_CLICKER_KEYBOARD("CrickSoftware - Clicker - Keyboard", "application/vnd.crick.clicker.keyboard", ".clkk"),
    CRICKSOFTWARE_CLICKER_PALETTE("CrickSoftware - Clicker - Palette", "application/vnd.crick.clicker.palette", ".clkp"),
    CRICKSOFTWARE_CLICKER_TEMPLATE("CrickSoftware - Clicker - Template", "application/vnd.crick.clicker.template", ".clkt"),
    CRICKSOFTWARE_CLICKER_WORDBANK("CrickSoftware - Clicker - Wordbank", "application/vnd.crick.clicker.wordbank", ".clkw"),
    CRITICAL_TOOLS_PERT_CHART_EXPERT("Critical Tools - PERT Chart EXPERT", "application/vnd.criticaltools.wbs+xml", ".wbs"),
    CRYPTONOTE("CryptoNote", "application/vnd.rig.cryptonote", ".cryptonote"),
    CRYSTALLOGRAPHIC_INTERCHANGE_FORMAT("Crystallographic Interchange Format", "chemical/x-cif", ".cif"),
    CRYSTALMAKER_DATA_FORMAT("CrystalMaker Data Format", "chemical/x-cmdf", ".cmdf"),
    CU_SEEME("CU-SeeMe", "application/cu-seeme", ".cu"),
    CU_WRITER("CU-Writer", "application/prs.cww", ".cww"),
    CURL_APPLET("Curl - Applet", "text/vnd.curl", ".curl"),
    CURL_DETACHED_APPLET("Curl - Detached Applet", "text/vnd.curl.dcurl", ".dcurl"),
    CURL_MANIFEST_FILE("Curl - Manifest File", "text/vnd.curl.mcurl", ".mcurl"),
    CURL_SOURCE_CODE("Curl - Source Code", "text/vnd.curl.scurl", ".scurl"),
    CURL_APPLET_CAR("CURL Applet", "application/vnd.curl.car", ".car"),
    CURL_APPLET_PCURL("CURL Applet", "application/vnd.curl.pcurl", ".pcurl"),
    CUSTOMMENU("CustomMenu", "application/vnd.yellowriver-custom-menu", ".cmp"),
    DATA_STRUCTURE_FOR_THE_SECURITY_SUITABILITY_OF_CRYPTOGRAPHIC_ALGORITHMS_DSSC("Data Structure for the Security Suitability of Cryptographic Algorithms", "application/dssc+der", ".dssc"),
    DATA_STRUCTURE_FOR_THE_SECURITY_SUITABILITY_OF_CRYPTOGRAPHIC_ALGORITHMS_XDSSC("Data Structure for the Security Suitability of Cryptographic Algorithms", "application/dssc+xml", ".xdssc"),
    DEBIAN_PACKAGE("Debian Package", "application/x-debian-package", ".deb"),
    DECE_AUDIO("DECE Audio", "audio/vnd.dece.audio", ".uva"),
    DECE_GRAPHIC("DECE Graphic", "image/vnd.dece.graphic", ".uvi"),
    DECE_HIGH_DEFINITION_VIDEO("DECE High Definition Video", "video/vnd.dece.hd", ".uvh"),
    DECE_MOBILE_VIDEO("DECE Mobile Video", "video/vnd.dece.mobile", ".uvm"),
    DECE_MP4("DECE MP4", "video/vnd.uvvu.mp4", ".uvu"),
    DECE_PD_VIDEO("DECE PD Video", "video/vnd.dece.pd", ".uvp"),
    DECE_SD_VIDEO("DECE SD Video", "video/vnd.dece.sd", ".uvs"),
    DECE_VIDEO("DECE Video", "video/vnd.dece.video", ".uvv"),
    DEVICE_INDEPENDENT_FILE_FORMAT_DVI("Device Independent File Format (DVI)", "application/x-dvi", ".dvi"),
    DIGITAL_SIESMOGRAPH_NETWORKS_SEED_DATAFILES("Digital Siesmograph Networks - SEED Datafiles", "application/vnd.fdsn.seed", ".seed"),
    DIGITAL_TALKING_BOOK("Digital Talking Book", "application/x-dtbook+xml", ".dtb"),
    DIGITAL_TALKING_BOOK_RESOURCE_FILE("Digital Talking Book - Resource File", "application/x-dtbresource+xml", ".res"),
    DIGITAL_VIDEO_BROADCASTING_AIT("Digital Video Broadcasting", "application/vnd.dvb.ait", ".ait"),
    DIGITAL_VIDEO_BROADCASTING_SVC("Digital Video Broadcasting", "application/vnd.dvb.service", ".svc"),
    DIGITAL_WINDS_MUSIC("Digital Winds Music", "audio/vnd.digital-winds", ".eol"),
    DJVU("DjVu", "image/vnd.djvu", ".djvu"),
    DOCUMENT_TYPE_DEFINITION("Document Type Definition", "application/xml-dtd", ".dtd"),
    DOLBY_MERIDIAN_LOSSLESS_PACKING("Dolby Meridian Lossless Packing", "application/vnd.dolby.mlp", ".mlp"),
    DOOM_VIDEO_GAME("Doom Video Game", "application/x-doom", ".wad"),
    DPGRAPH("DPGraph", "application/vnd.dpgraph", ".dpg"),
    DRA_AUDIO("DRA Audio", "audio/vnd.dra", ".dra"),
    DREAMFACTORY("DreamFactory", "application/vnd.dreamfactory", ".dfac"),
    DTS_AUDIO("DTS Audio", "audio/vnd.dts", ".dts"),
    DTS_HIGH_DEFINITION_AUDIO("DTS High Definition Audio", "audio/vnd.dts.hd", ".dtshd"),
    DWG_DRAWING("DWG Drawing", "image/vnd.dwg", ".dwg"),
    DYNAGEO("DynaGeo", "application/vnd.dynageo", ".geo"),
    ECMASCRIPT("ECMAScript", "application/ecmascript", ".es"),
    ECOWIN_CHART("EcoWin Chart", "application/vnd.ecowin.chart", ".mag"),
    EDMICS_2000_MMR("EDMICS 2000", "image/vnd.fujixerox.edmics-mmr", ".mmr"),
    EDMICS_2000_RLC("EDMICS 2000", "image/vnd.fujixerox.edmics-rlc", ".rlc"),
    EFFICIENT_XML_INTERCHANGE("Efficient XML Interchange", "application/exi", ".exi"),
    EFI_PROTEUS("EFI Proteus", "application/vnd.proteus.magazine", ".mgz"),
    ELECTRONIC_PUBLICATION("Electronic Publication", "application/epub+zip", ".epub"),
    EMAIL_MESSAGE("Email Message", "message/rfc822", ".eml"),
    ENLIVEN_VIEWER("Enliven Viewer", "application/vnd.enliven", ".nml"),
    EXPRESS_BY_INFOSEEK("Express by Infoseek", "application/vnd.is-xpr", ".xpr"),
    EXTENDED_IMAGE_FILE_FORMAT_XIFF("eXtended Image File Format (XIFF)", "image/vnd.xiff", ".xif"),
    EXTENSIBLE_FORMS_DESCRIPTION_LANGUAGE("Extensible Forms Description Language", "application/vnd.xfdl", ".xfdl"),
    EXTENSIBLE_MULTIMODAL_ANNOTATION("Extensible MultiModal Annotation", "application/emma+xml", ".emma"),
    EZPIX_SECURE_PHOTO_ALBUM_EZ2("EZPix Secure Photo Album", "application/vnd.ezpix-album", ".ez2"),
    EZPIX_SECURE_PHOTO_ALBUM_EZ3("EZPix Secure Photo Album", "application/vnd.ezpix-package", ".ez3"),
    FAST_SEARCH_TRANSFER_ASA_FST("FAST Search & Transfer ASA", "image/vnd.fst", ".fst"),
    FAST_SEARCH_TRANSFER_ASA_FVT("FAST Search & Transfer ASA", "video/vnd.fvt", ".fvt"),
    FASTBID_SHEET("FastBid Sheet", "image/vnd.fastbidsheet", ".fbs"),
    FCS_EXPRESS_LAYOUT_LINK("FCS Express Layout Link", "application/vnd.denovo.fcselayout-link", ".fe_launch"),
    FLASH_VIDEO_F4V("Flash Video", "video/x-f4v", ".f4v"),
    FLASH_VIDEO_FLV("Flash Video", "video/x-flv", ".flv"),
    FLASHPIX_FPX("FlashPix", "image/vnd.fpx", ".fpx"),
    FLASHPIX_NPX("FlashPix", "image/vnd.net-fpx", ".npx"),
    FLEXSTOR("FLEXSTOR", "text/vnd.fmi.flexstor", ".flx"),
    FLI_FLC_ANIMATION_FORMAT("FLI/FLC Animation Format", "video/x-fli", ".fli"),
    FLUXTIME_CLIP("FluxTime Clip", "application/vnd.fluxtime.clip", ".ftc"),
    FORMS_DATA_FORMAT("Forms Data Format", "application/vnd.fdf", ".fdf"),
    FORTRAN_SOURCE_FILE("Fortran Source File", "text/x-fortran", ".f"),
    FRAMEMAKER_INTERCHANGE_FORMAT("FrameMaker Interchange Format", "application/vnd.mif", ".mif"),
    FRAMEMAKER_NORMAL_FORMAT("FrameMaker Normal Format", "application/vnd.framemaker", ".fm"),
    FREEHAND_MX("FreeHand MX", "image/x-freehand", ".fh"),
    FRIENDLY_SOFTWARE_CORPORATION("Friendly Software Corporation", "application/vnd.fsc.weblaunch", ".fsc"),
    FROGANS_PLAYER_FNC("Frogans Player", "application/vnd.frogans.fnc", ".fnc"),
    FROGANS_PLAYER_LTF("Frogans Player", "application/vnd.frogans.ltf", ".ltf"),
    FUJITSU_XEROX_2D_CAD_DATA("Fujitsu - Xerox 2D CAD Data", "application/vnd.fujixerox.ddd", ".ddd"),
    FUJITSU_XEROX_DOCUWORKS("Fujitsu - Xerox DocuWorks", "application/vnd.fujixerox.docuworks", ".xdw"),
    FUJITSU_XEROX_DOCUWORKS_BINDER("Fujitsu - Xerox DocuWorks Binder", "application/vnd.fujixerox.docuworks.binder", ".xbd"),
    FUJITSU_OASYS_OAS("Fujitsu Oasys", "application/vnd.fujitsu.oasys", ".oas"),
    FUJITSU_OASYS_OA2("Fujitsu Oasys", "application/vnd.fujitsu.oasys2", ".oa2"),
    FUJITSU_OASYSOA3("Fujitsu Oasys", "application/vnd.fujitsu.oasys3", ".oa3"),
    FUJITSU_OASYS_FG5("Fujitsu Oasys", "application/vnd.fujitsu.oasysgp", ".fg5"),
    FUJITSU_OASYS_BH2("Fujitsu Oasys", "application/vnd.fujitsu.oasysprs", ".bh2"),
    FUTURESPLASH_ANIMATOR("FutureSplash Animator", "application/x-futuresplash", ".spl"),
    FUZZYSHEET("FuzzySheet", "application/vnd.fuzzysheet", ".fzs"),
    G3_FAX_IMAGE("G3 Fax Image", "image/g3fax", ".g3"),
    GAMEMAKER_ACTIVEX("GameMaker ActiveX", "application/vnd.gmx", ".gmx"),
    GEN_TRIX_STUDIO("Gen-Trix Studio", "model/vnd.gtw", ".gtw"),
    GENOMATIX_TUXEDO_FRAMEWORK("Genomatix Tuxedo Framework", "application/vnd.genomatix.tuxedo", ".txd"),
    GEOGEBRA_GGB("GeoGebra", "application/vnd.geogebra.file", ".ggb"),
    GEOGEBRA_GGT("GeoGebra", "application/vnd.geogebra.tool", ".ggt"),
    GEOMETRIC_DESCRIPTION_LANGUAGE_GDL("Geometric Description Language (GDL)", "model/vnd.gdl", ".gdl"),
    GEOMETRY_EXPLORER("GeoMetry Explorer", "application/vnd.geometry-explorer", ".gex"),
    GEONEXT_AND_JSXGRAPH("GEONExT and JSXGraph", "application/vnd.geonext", ".gxt"),
    GEOPLANW("GeoplanW", "application/vnd.geoplan", ".g2w"),
    GEOSPACW("GeospacW", "application/vnd.geospace", ".g3w"),
    GHOSTSCRIPT_FONT("Ghostscript Font", "application/x-font-ghostscript", ".gsf"),
    GLYPH_BITMAP_DISTRIBUTION_FORMAT("Glyph Bitmap Distribution Format", "application/x-font-bdf", ".bdf"),
    GNU_TAR_FILES("GNU Tar Files", "application/x-gtar", ".gtar"),
    GNU_TEXINFO_DOCUMENT("GNU Texinfo Document", "application/x-texinfo", ".texinfo"),
    GNUMERIC("Gnumeric", "application/x-gnumeric", ".gnumeric"),
    GOOGLE_EARTH_KML("Google Earth - KML", "application/vnd.google-earth.kml+xml", ".kml"),
    GOOGLE_EARTH_ZIPPED_KML("Google Earth - Zipped KML", "application/vnd.google-earth.kmz", ".kmz"),
    GPS_EXCHANGE_FORMAT("GPS eXchange Format", "application/gpx+xml", ".gpx"),
    GRAFEQ("GrafEq", "application/vnd.grafeq", ".gqf"),
    GRAPHICS_INTERCHANGE_FORMAT("Graphics Interchange Format", "image/gif", ".gif"),
    GRAPHVIZ("Graphviz", "text/vnd.graphviz", ".gv"),
    GROOVE_ACCOUNT("Groove - Account", "application/vnd.groove-account", ".gac"),
    GROOVE_HELP("Groove - Help", "application/vnd.groove-help", ".ghf"),
    GROOVE_IDENTITY_MESSAGE("Groove - Identity Message", "application/vnd.groove-identity-message", ".gim"),
    GROOVE_INJECTOR("Groove - Injector", "application/vnd.groove-injector", ".grv"),
    GROOVE_TOOL_MESSAGE("Groove - Tool Message", "application/vnd.groove-tool-message", ".gtm"),
    GROOVE_TOOL_TEMPLATE("Groove - Tool Template", "application/vnd.groove-tool-template", ".tpl"),
    GROOVE_VCARD("Groove - Vcard", "application/vnd.groove-vcard", ".vcg"),
    H_261("H.261", "video/h261", ".h261"),
    H_263("H.263", "video/h263", ".h263"),
    H_264("H.264", "video/h264", ".h264"),
    HEWLETT_PACKARD_INSTANT_DELIVERY("Hewlett Packard Instant Delivery", "application/vnd.hp-hpid", ".hpid"),
    HEWLETT_PACKARDS_WEBPRINTSMART("Hewlett-Packard's WebPrintSmart", "application/vnd.hp-hps", ".hps"),
    HIERARCHICAL_DATA_FORMAT("Hierarchical Data Format", "application/x-hdf", ".hdf"),
    HIT_N_MIX("Hit'n'Mix", "audio/vnd.rip", ".rip"),
    HOMEBANKING_COMPUTER_INTERFACE_HBCI("Homebanking Computer Interface (HBCI)", "application/vnd.hbci", ".hbci"),
    HP_INDIGO_DIGITAL_PRESS_JOB_LAYOUT_LANGUATE("HP Indigo Digital Press - Job Layout Languate", "application/vnd.hp-jlyt", ".jlt"),
    HP_PRINTER_COMMAND_LANGUAGE("HP Printer Command Language", "application/vnd.hp-pcl", ".pcl"),
    HP_GL_2_AND_HP_RTL("HP-GL/2 and HP RTL", "application/vnd.hp-hpgl", ".hpgl"),
    HV_SCRIPT("HV Script", "application/vnd.yamaha.hv-script", ".hvs"),
    HV_VOICE_DICTIONARY("HV Voice Dictionary", "application/vnd.yamaha.hv-dic", ".hvd"),
    HV_VOICE_PARAMETER("HV Voice Parameter", "application/vnd.yamaha.hv-voice", ".hvp"),
    HYDROSTATIX_MASTER_SUITE("Hydrostatix Master Suite", "application/vnd.hydrostatix.sof-data", ".sfd-hdstx"),
    HYPERSTUDIO("Hyperstudio", "application/hyperstudio", ".stk"),
    HYPERTEXT_APPLICATION_LANGUAGE("Hypertext Application Language", "application/vnd.hal+xml", ".hal"),
    HYPERTEXT_MARKUP_LANGUAGE__HTML("HyperText Markup Language (HTML)", "text/html", ".html"),
    IBM_DB2_RIGHTS_MANAGER("IBM DB2 Rights Manager", "application/vnd.ibm.rights-management", ".irm"),
    IBM_ELECTRONIC_MEDIA_MANAGEMENT_SYSTEM_SECURE_CONTAINER("IBM Electronic Media Management System - Secure Container", "application/vnd.ibm.secure-container", ".sc"),
    ICALENDAR("iCalendar", "text/calendar", ".ics"),
    ICC_PROFILE("ICC profile", "application/vnd.iccprofile", ".icc"),
    ICON_IMAGE("Icon Image", "image/x-icon", ".ico"),
    IGLOADER("igLoader", "application/vnd.igloader", ".igl"),
    IMAGE_EXCHANGE_FORMAT("Image Exchange Format", "image/ief", ".ief"),
    IMMERVISION_PURE_PLAYERS_IVP("ImmerVision PURE Players", "application/vnd.immervision-ivp", ".ivp"),
    IMMERVISION_PURE_PLAYERS_IVU("ImmerVision PURE Players", "application/vnd.immervision-ivu", ".ivu"),
    IMS_NETWORKS("IMS Networks", "application/reginfo+xml", ".rif"),
    IN3D_3DML("In3D - 3DML", "text/vnd.in3d.3dml", ".3dml"),
    IN3D_SPOT("In3D - SPOT", "text/vnd.in3d.spot", ".spot"),
    INITIAL_GRAPHICS_EXCHANGE_SPECIFICATION_IGES("Initial Graphics Exchange Specification (IGES)", "model/iges", ".igs"),
    INTERACTIVE_GEOMETRY_SOFTWARE("Interactive Geometry Software", "application/vnd.intergeo", ".i2g"),
    INTERACTIVE_GEOMETRY_SOFTWARE_CINDERELLA("Interactive Geometry Software Cinderella", "application/vnd.cinderella", ".cdy"),
    INTERCON_FORMNET("Intercon FormNet", "application/vnd.intercon.formnet", ".xpw"),
    INTERNATIONAL_SOCIETY_FOR_ADVANCEMENT_OF_CYTOMETRY("International Society for Advancement of Cytometry", "application/vnd.isac.fcs", ".fcs"),
    INTERNET_PROTOCOL_FLOW_INFORMATION_EXPORT("Internet Protocol Flow Information Export", "application/ipfix", ".ipfix"),
    INTERNET_PUBLIC_KEY_INFRASTRUCTURE_CERTIFICATE("Internet Public Key Infrastructure - Certificate", "application/pkix-cert", ".cer"),
    INTERNET_PUBLIC_KEY_INFRASTRUCTURE_CERTIFICATE_MANAGEMENT_PROTOCOLE("Internet Public Key Infrastructure - Certificate Management Protocole", "application/pkixcmp", ".pki"),
    INTERNET_PUBLIC_KEY_INFRASTRUCTURE_CERTIFICATE_REVOCATION_LISTS("Internet Public Key Infrastructure - Certificate Revocation Lists", "application/pkix-crl", ".crl"),
    INTERNET_PUBLIC_KEY_INFRASTRUCTURE_CERTIFICATION_PATH("Internet Public Key Infrastructure - Certification Path", "application/pkix-pkipath", ".pkipath"),
    IOCOM_VISIMEET("IOCOM Visimeet", "application/vnd.insors.igm", ".igm"),
    IP_UNPLUGGED_ROAMING_CLIENT("IP Unplugged Roaming Client", "application/vnd.ipunplugged.rcprofile", ".rcprofile"),
    IREPOSITORY_LUCIDOC_EDITOR("iRepository / Lucidoc Editor", "application/vnd.irepository.package+xml", ".irp"),
    J2ME_APP_DESCRIPTOR("J2ME App Descriptor", "text/vnd.sun.j2me.app-descriptor", ".jad"),
    JAVA_ARCHIVE("Java Archive", "application/java-archive", ".jar"),
    JAVA_BYTECODE_FILE("Java Bytecode File", "application/java-vm", ".class"),
    JAVA_NETWORK_LAUNCHING_PROTOCOL("Java Network Launching Protocol", "application/x-java-jnlp-file", ".jnlp"),
    JAVA_SERIALIZED_OBJECT("Java Serialized Object", "application/java-serialized-object", ".ser"),
    JAVA_SOURCE_FILE("Java Source File", "text/x-java-source,java", ".java"),
    JAVASCRIPT("JavaScript", "application/javascript", ".js"),
    JAVASCRIPT_OBJECT_NOTATION_JSON("JavaScript Object Notation (JSON)", "application/json", ".json"),
    JODA_ARCHIVE("Joda Archive", "application/vnd.joost.joda-archive", ".joda"),
    JPEG_2000_COMPOUND_IMAGE_FILE_FORMAT("JPEG 2000 Compound Image File Format", "video/jpm", ".jpm"),
    JPG_IMAGE("JPEG Image", "image/jpeg", ".jpg"),
    JPEG_IMAGE("JPEG Image", "image/jpeg", ".jpeg"),
    JPEG_IMAGE_CITRIX_CLIENT("JPEG Image (Citrix client)", "image/x-citrix-jpeg", ".jpeg"),
    JPG_IMAGE_CITRIX_CLIENT("JPEG Image (Citrix client)", "image/x-citrix-jpeg", ".jpg"),
    JPEG_IMAGE_PROGRESSIVE("JPEG Image (Progressive)", "image/pjpeg", ".pjpeg"),
    JPGVIDEO("JPGVideo", "video/jpeg", ".jpgv"),
    KAHOOTZ("Kahootz", "application/vnd.kahootz", ".ktz"),
    KARAOKE_ON_CHIPNUTS_CHIPSETS("Karaoke on Chipnuts Chipsets", "application/vnd.chipnuts.karaoke-mmd", ".mmd"),
    KDE_KOFFICE_OFFICE_SUITE_KARBON("KDE KOffice Office Suite - Karbon", "application/vnd.kde.karbon", ".karbon"),
    KDE_KOFFICE_OFFICE_SUITE_KCHART("KDE KOffice Office Suite - KChart", "application/vnd.kde.kchart", ".chrt"),
    KDE_KOFFICE_OFFICE_SUITE_KFORMULA("KDE KOffice Office Suite - Kformula", "application/vnd.kde.kformula", ".kfo"),
    KDE_KOFFICE_OFFICE_SUITE_KIVIO("KDE KOffice Office Suite - Kivio", "application/vnd.kde.kivio", ".flw"),
    KDE_KOFFICE_OFFICE_SUITE_KONTOUR("KDE KOffice Office Suite - Kontour", "application/vnd.kde.kontour", ".kon"),
    KDE_KOFFICE_OFFICE_SUITE_KPRESENTER("KDE KOffice Office Suite - Kpresenter", "application/vnd.kde.kpresenter", ".kpr"),
    KDE_KOFFICE_OFFICE_SUITE_KSPREAD("KDE KOffice Office Suite - Kspread", "application/vnd.kde.kspread", ".ksp"),
    KDE_KOFFICE_OFFICE_SUITE_KWORD("KDE KOffice Office Suite - Kword", "application/vnd.kde.kword", ".kwd"),
    KENAMEA_APP("Kenamea App", "application/vnd.kenameaapp", ".htke"),
    KIDSPIRATION("Kidspiration", "application/vnd.kidspiration", ".kia"),
    KINAR_APPLICATIONS("Kinar Applications", "application/vnd.kinar", ".kne"),
    KODAK_STORYSHARE("Kodak Storyshare", "application/vnd.kodak-descriptor", ".sse"),
    LASER_APP_ENTERPRISE("Laser App Enterprise", "application/vnd.las.las+xml", ".lasxml"),
    LATEX("LaTeX", "application/x-latex", ".latex"),
    LIFE_BALANCE_DESKTOP_EDITION("Life Balance - Desktop Edition", "application/vnd.llamagraphics.life-balance.desktop", ".lbd"),
    LIFE_BALANCE_EXCHANGE_FORMAT("Life Balance - Exchange Format", "application/vnd.llamagraphics.life-balance.exchange+xml", ".lbe"),
    LIGHTSPEED_AUDIO_LAB("Lightspeed Audio Lab", "application/vnd.jam", ".jam"),
    LOTUS_1_2_3("Lotus 1-2-3", "application/vnd.lotus-1-2-3", ".123"),
    LOTUS_APPROACH("Lotus Approach", "application/vnd.lotus-approach", ".apr"),
    LOTUS_FREELANCE("Lotus Freelance", "application/vnd.lotus-freelance", ".pre"),
    LOTUS_NOTES("Lotus Notes", "application/vnd.lotus-notes", ".nsf"),
    LOTUS_ORGANIZER("Lotus Organizer", "application/vnd.lotus-organizer", ".org"),
    LOTUS_SCREENCAM("Lotus Screencam", "application/vnd.lotus-screencam", ".scm"),
    LOTUS_WORDPRO("Lotus Wordpro", "application/vnd.lotus-wordpro", ".lwp"),
    LUCENT_VOICE("Lucent Voice", "audio/vnd.lucent.voice", ".lvp"),
    M3U_MULTIMEDIA_PLAYLIST("M3U (Multimedia Playlist)", "audio/x-mpegurl", ".m3u"),
    M4V("M4v", "video/x-m4v", ".m4v"),
    MACINTOSH_BINHEX_4_0("Macintosh BinHex 4.0", "application/mac-binhex40", ".hqx"),
    MACPORTS_PORT_SYSTEM("MacPorts Port System", "application/vnd.macports.portpkg", ".portpkg"),
    MAPGUIDE_DBXML("MapGuide DBXML", "application/vnd.osgeo.mapguide.package", ".mgp"),
    MARC_FORMATS("MARC Formats", "application/marc", ".mrc"),
    MARC21_XML_SCHEMA("MARC21 XML Schema", "application/marcxml+xml", ".mrcx"),
    MATERIAL_EXCHANGE_FORMAT("Material Exchange Format", "application/mxf", ".mxf"),
    MATHEMATICA_NOTEBOOK_PLAYER("Mathematica Notebook Player", "application/vnd.wolfram.player", ".nbp"),
    MATHEMATICA_NOTEBOOKS("Mathematica Notebooks", "application/mathematica", ".ma"),
    MATHEMATICAL_MARKUP_LANGUAGE("Mathematical Markup Language", "application/mathml+xml", ".mathml"),
    MBOX_DATABASE_FILES("Mbox database files", "application/mbox", ".mbox"),
    MEDCALC("MedCalc", "application/vnd.medcalcdata", ".mc1"),
    MEDIA_SERVER_CONTROL_MARKUP_LANGUAGE("Media Server Control Markup Language", "application/mediaservercontrol+xml", ".mscml"),
    MEDIAREMOTE("MediaRemote", "application/vnd.mediastation.cdkey", ".cdkey"),
    MEDICAL_WAVEFORM_ENCODING_FORMAT("Medical Waveform Encoding Format", "application/vnd.mfer", ".mwf"),
    MELODY_FORMAT_FOR_MOBILE_PLATFORM("Melody Format for Mobile Platform", "application/vnd.mfmp", ".mfm"),
    MESH_DATA_TYPE("Mesh Data Type", "model/mesh", ".msh"),
    METADATA_AUTHORITY_DESCRIPTION_SCHEMA("Metadata Authority Description Schema", "application/mads+xml", ".mads"),
    METADATA_ENCODING_AND_TRANSMISSION_STANDARD("Metadata Encoding and Transmission Standard", "application/mets+xml", ".mets"),
    METADATA_OBJECT_DESCRIPTION_SCHEMA("Metadata Object Description Schema", "application/mods+xml", ".mods"),
    METALINK("Metalink", "application/metalink4+xml", ".meta4"),
    MICRO_CADAM_HELIX_D_D("Micro CADAM Helix D&D", "application/vnd.mcd", ".mcd"),
    MICROGRAFX("Micrografx", "application/vnd.micrografx.flo", ".flo"),
    MICROGRAFX_IGRAFX_PROFESSIONAL("Micrografx iGrafx Professional", "application/vnd.micrografx.igx", ".igx"),
    MICROSEC_E_SZIGN_("MICROSEC e-Szignï¿½", "application/vnd.eszigno3+xml", ".es3"),
    MICROSOFT_ACCESS("Microsoft Access", "application/x-msaccess", ".mdb"),
    MICROSOFT_ADVANCED_SYSTEMS_FORMAT_ASF("Microsoft Advanced Systems Format (ASF)", "video/x-ms-asf", ".asf"),
    MICROSOFT_APPLICATION("Microsoft Application", "application/x-msdownload", ".exe"),
    MICROSOFT_ARTGALRY("Microsoft Artgalry", "application/vnd.ms-artgalry", ".cil"),
    MICROSOFT_CABINET_FILE("Microsoft Cabinet File", "application/vnd.ms-cab-compressed", ".cab"),
    MICROSOFT_CLASS_SERVER("Microsoft Class Server", "application/vnd.ms-ims", ".ims"),
    MICROSOFT_CLICKONCE("Microsoft ClickOnce", "application/x-ms-application", ".application"),
    MICROSOFT_CLIPBOARD_CLIP("Microsoft Clipboard Clip", "application/x-msclip", ".clp"),
    MICROSOFT_DOCUMENT_IMAGING_FORMAT("Microsoft Document Imaging Format", "image/vnd.ms-modi", ".mdi"),
    MICROSOFT_EMBEDDED_OPENTYPE("Microsoft Embedded OpenType", "application/vnd.ms-fontobject", ".eot"),
    MICROSOFT_EXCEL("Microsoft Excel", "application/vnd.ms-excel", ".xls"),
    MICROSOFT_EXCEL_ADD_IN_FILE("Microsoft Excel - Add-In File", "application/vnd.ms-excel.addin.macroenabled.12", ".xlam"),
    MICROSOFT_EXCEL_BINARY_WORKBOOK("Microsoft Excel - Binary Workbook", "application/vnd.ms-excel.sheet.binary.macroenabled.12", ".xlsb"),
    MICROSOFT_EXCEL_MACRO_ENABLED_TEMPLATE_FILE("Microsoft Excel - Macro-Enabled Template File", "application/vnd.ms-excel.template.macroenabled.12", ".xltm"),
    MICROSOFT_EXCEL_MACRO_ENABLED_WORKBOOK("Microsoft Excel - Macro-Enabled Workbook", "application/vnd.ms-excel.sheet.macroenabled.12", ".xlsm"),
    MICROSOFT_HTML_HELP_FILE("Microsoft Html Help File", "application/vnd.ms-htmlhelp", ".chm"),
    MICROSOFT_INFORMATION_CARD("Microsoft Information Card", "application/x-mscardfile", ".crd"),
    MICROSOFT_LEARNING_RESOURCE_MODULE("Microsoft Learning Resource Module", "application/vnd.ms-lrm", ".lrm"),
    MICROSOFT_MEDIAVIEW("Microsoft MediaView", "application/x-msmediaview", ".mvb"),
    MICROSOFT_MONEY("Microsoft Money", "application/x-msmoney", ".mny"),
    MICROSOFT_OFFICE_OOXML_PRESENTATION("Microsoft Office - OOXML - Presentation", "application/vnd.openxmlformats-officedocument.presentationml.presentation", ".pptx"),
    MICROSOFT_OFFICE_OOXML_PRESENTATION_SLIDE("Microsoft Office - OOXML - Presentation (Slide)", "application/vnd.openxmlformats-officedocument.presentationml.slide", ".sldx"),
    MICROSOFT_OFFICE_OOXML_PRESENTATION_SLIDESHOW("Microsoft Office - OOXML - Presentation (Slideshow)", "application/vnd.openxmlformats-officedocument.presentationml.slideshow", ".ppsx"),
    MICROSOFT_OFFICE_OOXML_PRESENTATION_TEMPLATE("Microsoft Office - OOXML - Presentation Template", "application/vnd.openxmlformats-officedocument.presentationml.template", ".potx"),
    MICROSOFT_OFFICE_OOXML_SPREADSHEET("Microsoft Office - OOXML - Spreadsheet", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", ".xlsx"),
    MICROSOFT_OFFICE_OOXML_SPREADSHEET_TEMPLATE("Microsoft Office - OOXML - Spreadsheet Template", "application/vnd.openxmlformats-officedocument.spreadsheetml.template", ".xltx"),
    MICROSOFT_OFFICE_OOXML_WORD_DOCUMENT("Microsoft Office - OOXML - Word Document", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", ".docx"),
    MICROSOFT_OFFICE_OOXML_WORD_DOCUMENT_TEMPLATE("Microsoft Office - OOXML - Word Document Template", "application/vnd.openxmlformats-officedocument.wordprocessingml.template", ".dotx"),
    MICROSOFT_OFFICE_BINDER("Microsoft Office Binder", "application/x-msbinder", ".obd"),
    MICROSOFT_OFFICE_SYSTEM_RELEASE_THEME("Microsoft Office System Release Theme", "application/vnd.ms-officetheme", ".thmx"),
    MICROSOFT_ONENOTE("Microsoft OneNote", "application/onenote", ".onetoc"),
    MICROSOFT_PLAYREADY_ECOSYSTEM("Microsoft PlayReady Ecosystem", "audio/vnd.ms-playready.media.pya", ".pya"),
    MICROSOFT_PLAYREADY_ECOSYSTEM_VIDEO("Microsoft PlayReady Ecosystem Video", "video/vnd.ms-playready.media.pyv", ".pyv"),
    MICROSOFT_POWERPOINT("Microsoft PowerPoint", "application/vnd.ms-powerpoint", ".ppt"),
    MICROSOFT_POWERPOINT_ADD_IN_FILE("Microsoft PowerPoint - Add-in file", "application/vnd.ms-powerpoint.addin.macroenabled.12", ".ppam"),
    MICROSOFT_POWERPOINT_MACRO_ENABLED_OPEN_XML_SLIDE("Microsoft PowerPoint - Macro-Enabled Open XML Slide", "application/vnd.ms-powerpoint.slide.macroenabled.12", ".sldm"),
    MICROSOFT_POWERPOINT_MACRO_ENABLED_PRESENTATION_FILE("Microsoft PowerPoint - Macro-Enabled Presentation File", "application/vnd.ms-powerpoint.presentation.macroenabled.12", ".pptm"),
    MICROSOFT_POWERPOINT_MACRO_ENABLED_SLIDE_SHOW_FILE("Microsoft PowerPoint - Macro-Enabled Slide Show File", "application/vnd.ms-powerpoint.slideshow.macroenabled.12", ".ppsm"),
    MICROSOFT_POWERPOINT_MACRO_ENABLED_TEMPLATE_FILE("Microsoft PowerPoint - Macro-Enabled Template File", "application/vnd.ms-powerpoint.template.macroenabled.12", ".potm"),
    MICROSOFT_PROJECT("Microsoft Project", "application/vnd.ms-project", ".mpp"),
    MICROSOFT_PUBLISHER("Microsoft Publisher", "application/x-mspublisher", ".pub"),
    MICROSOFT_SCHEDULE("Microsoft Schedule+", "application/x-msschedule", ".scd"),
    MICROSOFT_SILVERLIGHT("Microsoft Silverlight", "application/x-silverlight-app", ".xap"),
    MICROSOFT_TRUST_UI_PROVIDER_CERTIFICATE_TRUST_LINK("Microsoft Trust UI Provider - Certificate Trust Link", "application/vnd.ms-pki.stl", ".stl"),
    MICROSOFT_TRUST_UI_PROVIDER_SECURITY_CATALOG("Microsoft Trust UI Provider - Security Catalog", "application/vnd.ms-pki.seccat", ".cat"),
    MICROSOFT_VISIO("Microsoft Visio", "application/vnd.visio", ".vsd"),
    MICROSOFT_VISIO_2013("Microsoft Visio 2013", "application/vnd.visio2013", ".vsdx"),
    MICROSOFT_WINDOWS_MEDIA("Microsoft Windows Media", "video/x-ms-wm", ".wm"),
    MICROSOFT_WINDOWS_MEDIA_AUDIO("Microsoft Windows Media Audio", "audio/x-ms-wma", ".wma"),
    MICROSOFT_WINDOWS_MEDIA_AUDIO_REDIRECTOR("Microsoft Windows Media Audio Redirector", "audio/x-ms-wax", ".wax"),
    MICROSOFT_WINDOWS_MEDIA_AUDIO_VIDEO_PLAYLIST("Microsoft Windows Media Audio/Video Playlist", "video/x-ms-wmx", ".wmx"),
    MICROSOFT_WINDOWS_MEDIA_PLAYER_DOWNLOAD_PACKAGE("Microsoft Windows Media Player Download Package", "application/x-ms-wmd", ".wmd"),
    MICROSOFT_WINDOWS_MEDIA_PLAYER_PLAYLIST("Microsoft Windows Media Player Playlist", "application/vnd.ms-wpl", ".wpl"),
    MICROSOFT_WINDOWS_MEDIA_PLAYER_SKIN_PACKAGE("Microsoft Windows Media Player Skin Package", "application/x-ms-wmz", ".wmz"),
    MICROSOFT_WINDOWS_MEDIA_VIDEO("Microsoft Windows Media Video", "video/x-ms-wmv", ".wmv"),
    MICROSOFT_WINDOWS_MEDIA_VIDEO_PLAYLIST("Microsoft Windows Media Video Playlist", "video/x-ms-wvx", ".wvx"),
    MICROSOFT_WINDOWS_METAFILE("Microsoft Windows Metafile", "application/x-msmetafile", ".wmf"),
    MICROSOFT_WINDOWS_TERMINAL_SERVICES("Microsoft Windows Terminal Services", "application/x-msterminal", ".trm"),
    MICROSOFT_WORD("Microsoft Word", "application/msword", ".doc"),
    MICROSOFT_WORD_MACRO_ENABLED_DOCUMENT("Microsoft Word - Macro-Enabled Document", "application/vnd.ms-word.document.macroenabled.12", ".docm"),
    MICROSOFT_WORD_MACRO_ENABLED_TEMPLATE("Microsoft Word - Macro-Enabled Template", "application/vnd.ms-word.template.macroenabled.12", ".dotm"),
    MICROSOFT_WORDPAD("Microsoft Wordpad", "application/x-mswrite", ".wri"),
    MICROSOFT_WORKS("Microsoft Works", "application/vnd.ms-works", ".wps"),
    MICROSOFT_XAML_BROWSER_APPLICATION("Microsoft XAML Browser Application", "application/x-ms-xbap", ".xbap"),
    MICROSOFT_XML_PAPER_SPECIFICATION("Microsoft XML Paper Specification", "application/vnd.ms-xpsdocument", ".xps"),
    MIDI_MUSICAL_INSTRUMENT_DIGITAL_INTERFACE("MIDI - Musical Instrument Digital Interface", "audio/midi", ".mid"),
    MINIPAY("MiniPay", "application/vnd.ibm.minipay", ".mpy"),
    MO_DCA_P("MO:DCA-P", "application/vnd.ibm.modcap", ".afp"),
    MOBILE_INFORMATION_DEVICE_PROFILE("Mobile Information Device Profile", "application/vnd.jcp.javame.midlet-rms", ".rms"),
    MOBILETV("MobileTV", "application/vnd.tmobile-livetv", ".tmo"),
    MOBIPOCKET("Mobipocket", "application/x-mobipocket-ebook", ".prc"),
    MOBIUS_MANAGEMENT_SYSTEMS_BASKET_FILE("Mobius Management Systems - Basket file", "application/vnd.mobius.mbk", ".mbk"),
    MOBIUS_MANAGEMENT_SYSTEMS_DISTRIBUTION_DATABASE("Mobius Management Systems - Distribution Database", "application/vnd.mobius.dis", ".dis"),
    MOBIUS_MANAGEMENT_SYSTEMS_POLICY_DEFINITION_LANGUAGE_FILE("Mobius Management Systems - Policy Definition Language File", "application/vnd.mobius.plc", ".plc"),
    MOBIUS_MANAGEMENT_SYSTEMS_QUERY_FILE("Mobius Management Systems - Query File", "application/vnd.mobius.mqy", ".mqy"),
    MOBIUS_MANAGEMENT_SYSTEMS_SCRIPT_LANGUAGE("Mobius Management Systems - Script Language", "application/vnd.mobius.msl", ".msl"),
    MOBIUS_MANAGEMENT_SYSTEMS_TOPIC_INDEX_FILE("Mobius Management Systems - Topic Index File", "application/vnd.mobius.txf", ".txf"),
    MOBIUS_MANAGEMENT_SYSTEMS_UNIVERSALARCHIVE("Mobius Management Systems - UniversalArchive", "application/vnd.mobius.daf", ".daf"),
    MOD_FLY_FLY_CGI("mod_fly / fly.cgi", "text/vnd.fly", ".fly"),
    MOPHUN_CERTIFICATE("Mophun Certificate", "application/vnd.mophun.certificate", ".mpc"),
    MOPHUN_VM("Mophun VM", "application/vnd.mophun.application", ".mpn"),
    MOTION_JPEG_2000("Motion JPEG 2000", "video/mj2", ".mj2"),
    MPEG_AUDIO("MPEG Audio", "audio/mpeg", ".mpga"),
    MPEG_URL("MPEG Url", "video/vnd.mpegurl", ".mxu"),
    MPEG_VIDEO("MPEG Video", "video/mpeg", ".mpeg"),
    MPEG_21("MPEG-21", "application/mp21", ".m21"),
    MPEG_4_AUDIO("MPEG-4 Audio", "audio/mp4", ".mp4a"),
    MPEG_4_VIDEO("MPEG-4 Video", "video/mp4", ".mp4"),
    MPEG4("MPEG4", "application/mp4", ".mp4"),
    MULTIMEDIA_PLAYLIST_UNICODE("Multimedia Playlist Unicode", "application/vnd.apple.mpegurl", ".m3u8"),
    MUSICAL_SCORE_INTERPRETED_CODE_INVENTED_FOR_THE_ASCII_DESIGNATION_OF_NOTATION("MUsical Score Interpreted Code Invented for the ASCII designation of Notation", "application/vnd.musician", ".mus"),
    MUVEE_AUTOMATIC_VIDEO_EDITING("Muvee Automatic Video Editing", "application/vnd.muvee.style", ".msty"),
    MXML("MXML", "application/xv+xml", ".mxml"),
    N_GAGE_GAME_DATA("N-Gage Game Data", "application/vnd.nokia.n-gage.data", ".ngdat"),
    N_GAGE_GAME_INSTALLER("N-Gage Game Installer", "application/vnd.nokia.n-gage.symbian.install", ".n-gage"),
    NAVIGATION_CONTROL_FILE_FOR_XML_FOR_EPUB("Navigation Control file for XML (for ePub)", "application/x-dtbncx+xml", ".ncx"),
    NETWORK_COMMON_DATA_FORM_NETCDF("Network Common Data Form (NetCDF)", "application/x-netcdf", ".nc"),
    NEUROLANGUAGE("neuroLanguage", "application/vnd.neurolanguage.nlu", ".nlu"),
    NEW_MOON_LIFTOFF_DNA("New Moon Liftoff/DNA", "application/vnd.dna", ".dna"),
    NOBLENET_DIRECTORY("NobleNet Directory", "application/vnd.noblenet-directory", ".nnd"),
    NOBLENET_SEALER("NobleNet Sealer", "application/vnd.noblenet-sealer", ".nns"),
    NOBLENET_WEB("NobleNet Web", "application/vnd.noblenet-web", ".nnw"),
    NOKIA_RADIO_APPLICATION_PRESET_RPST("Nokia Radio Application - Preset", "application/vnd.nokia.radio-preset", ".rpst"),
    NOKIA_RADIO_APPLICATION_PRESET_RPSS("Nokia Radio Application - Preset", "application/vnd.nokia.radio-presets", ".rpss"),
    NOTATION3("Notation3", "text/n3", ".n3"),
    NOVADIGMS_RADIA_AND_EDM_PRODUCTS_EDM("Novadigm's RADIA and EDM products", "application/vnd.novadigm.edm", ".edm"),
    NOVADIGMS_RADIA_AND_EDM_PRODUCTS_EDX("Novadigm's RADIA and EDM products", "application/vnd.novadigm.edx", ".edx"),
    NOVADIGMS_RADIA_AND_EDM_PRODUCTS_EXT("Novadigm's RADIA and EDM products", "application/vnd.novadigm.ext", ".ext"),
    NPGRAPHIT("NpGraphIt", "application/vnd.flographit", ".gph"),
    NUERA_ECELP_4800("Nuera ECELP 4800", "audio/vnd.nuera.ecelp4800", ".ecelp4800"),
    NUERA_ECELP_7470("Nuera ECELP 7470", "audio/vnd.nuera.ecelp7470", ".ecelp7470"),
    NUERA_ECELP_9600("Nuera ECELP 9600", "audio/vnd.nuera.ecelp9600", ".ecelp9600"),
    OFFICE_DOCUMENT_ARCHITECTURE_APPLICATION_ODA("Office Document Architecture", "application/oda", ".oda"),
    OGG("Ogg", "application/ogg", ".ogx"),
    OGG_AUDIO("Ogg Audio", "audio/ogg", ".oga"),
    OGG_VIDEO("Ogg Video", "video/ogg", ".ogv"),
    OMA_DOWNLOAD_AGENTS("OMA Download Agents", "application/vnd.oma.dd2+xml", ".dd2"),
    OPEN_DOCUMENT_TEXT_WEB("Open Document Text Web", "application/vnd.oasis.opendocument.text-web", ".oth"),
    OPEN_EBOOK_PUBLICATION_STRUCTURE("Open eBook Publication Structure", "application/oebps-package+xml", ".opf"),
    OPEN_FINANCIAL_EXCHANGE("Open Financial Exchange", "application/vnd.intu.qbo", ".qbo"),
    OPEN_OFFICE_EXTENSION("Open Office Extension", "application/vnd.openofficeorg.extension", ".oxt"),
    OPEN_SCORE_FORMAT("Open Score Format", "application/vnd.yamaha.openscoreformat", ".osf"),
    OPEN_WEB_MEDIA_PROJECT_AUDIO("Open Web Media Project - Audio", "audio/webm", ".weba"),
    OPEN_WEB_MEDIA_PROJECT_VIDEO("Open Web Media Project - Video", "video/webm", ".webm"),
    OPENDOCUMENT_CHART("OpenDocument Chart", "application/vnd.oasis.opendocument.chart", ".odc"),
    OPENDOCUMENT_CHART_TEMPLATE("OpenDocument Chart Template", "application/vnd.oasis.opendocument.chart-template", ".otc"),
    OPENDOCUMENT_DATABASE("OpenDocument Database", "application/vnd.oasis.opendocument.database", ".odb"),
    OPENDOCUMENT_FORMULA("OpenDocument Formula", "application/vnd.oasis.opendocument.formula", ".odf"),
    OPENDOCUMENT_FORMULA_TEMPLATE("OpenDocument Formula Template", "application/vnd.oasis.opendocument.formula-template", ".odft"),
    OPENDOCUMENT_GRAPHICS("OpenDocument Graphics", "application/vnd.oasis.opendocument.graphics", ".odg"),
    OPENDOCUMENT_GRAPHICS_TEMPLATE("OpenDocument Graphics Template", "application/vnd.oasis.opendocument.graphics-template", ".otg"),
    OPENDOCUMENT_IMAGE("OpenDocument Image", "application/vnd.oasis.opendocument.image", ".odi"),
    OPENDOCUMENT_IMAGE_TEMPLATE("OpenDocument Image Template", "application/vnd.oasis.opendocument.image-template", ".oti"),
    OPENDOCUMENT_PRESENTATION("OpenDocument Presentation", "application/vnd.oasis.opendocument.presentation", ".odp"),
    OPENDOCUMENT_PRESENTATION_TEMPLATE("OpenDocument Presentation Template", "application/vnd.oasis.opendocument.presentation-template", ".otp"),
    OPENDOCUMENT_SPREADSHEET("OpenDocument Spreadsheet", "application/vnd.oasis.opendocument.spreadsheet", ".ods"),
    OPENDOCUMENT_SPREADSHEET_TEMPLATE("OpenDocument Spreadsheet Template", "application/vnd.oasis.opendocument.spreadsheet-template", ".ots"),
    OPENDOCUMENT_TEXT("OpenDocument Text", "application/vnd.oasis.opendocument.text", ".odt"),
    OPENDOCUMENT_TEXT_MASTER("OpenDocument Text Master", "application/vnd.oasis.opendocument.text-master", ".odm"),
    OPENDOCUMENT_TEXT_TEMPLATE("OpenDocument Text Template", "application/vnd.oasis.opendocument.text-template", ".ott"),
    OPENGL_TEXTURES_KTX("OpenGL Textures (KTX)", "image/ktx", ".ktx"),
    OPENOFFICE_CALC_SPREADSHEET("OpenOffice - Calc (Spreadsheet)", "application/vnd.sun.xml.calc", ".sxc"),
    OPENOFFICE_CALC_TEMPLATE_SPREADSHEET("OpenOffice - Calc Template (Spreadsheet)", "application/vnd.sun.xml.calc.template", ".stc"),
    OPENOFFICE_DRAW_GRAPHICS("OpenOffice - Draw (Graphics)", "application/vnd.sun.xml.draw", ".sxd"),
    OPENOFFICE_DRAW_TEMPLATE_GRAPHICS("OpenOffice - Draw Template (Graphics)", "application/vnd.sun.xml.draw.template", ".std"),
    OPENOFFICE_IMPRESS_PRESENTATION("OpenOffice - Impress (Presentation)", "application/vnd.sun.xml.impress", ".sxi"),
    OPENOFFICE_IMPRESS_TEMPLATE_PRESENTATION("OpenOffice - Impress Template (Presentation)", "application/vnd.sun.xml.impress.template", ".sti"),
    OPENOFFICE_MATH_FORMULA("OpenOffice - Math (Formula)", "application/vnd.sun.xml.math", ".sxm"),
    OPENOFFICE_WRITER_TEXT_HTML_SXW("OpenOffice - Writer (Text - HTML)", "application/vnd.sun.xml.writer", ".sxw"),
    OPENOFFICE_WRITER_TEXT_HTML_SXG("OpenOffice - Writer (Text - HTML)", "application/vnd.sun.xml.writer.global", ".sxg"),
    OPENOFFICE_WRITER_TEMPLATE_TEXT_HTML("OpenOffice - Writer Template (Text - HTML)", "application/vnd.sun.xml.writer.template", ".stw"),
    OPENTYPE_FONT_FILE("OpenType Font File", "application/x-font-otf", ".otf"),
    OSFPVG("OSFPVG", "application/vnd.yamaha.openscoreformat.osfpvg+xml", ".osfpvg"),
    OSGI_DEPLOYMENT_PACKAGE("OSGi Deployment Package", "application/vnd.osgi.dp", ".dp"),
    PALMOS_DATA("PalmOS Data", "application/vnd.palm", ".pdb"),
    PASCAL_SOURCE_FILE("Pascal Source File", "text/x-pascal", ".p"),
    PAWAAFILE("PawaaFILE", "application/vnd.pawaafile", ".paw"),
    PCL_6_ENHANCED_FORMELY_PCL_XL("PCL 6 Enhanced (Formely PCL XL)", "application/vnd.hp-pclxl", ".pclxl"),
    PCSEL_EFIF_FILE("Pcsel eFIF File", "application/vnd.picsel", ".efif"),
    PCX_IMAGE("PCX Image", "image/x-pcx", ".pcx"),
    PHOTOSHOP_DOCUMENT("Photoshop Document", "image/vnd.adobe.photoshop", ".psd"),
    PICSRULES("PICSRules", "application/pics-rules", ".prf"),
    PICT_IMAGE("PICT Image", "image/x-pict", ".pic"),
    PIRCH("pIRCh", "application/x-chat", ".chat"),
    PKCS_10_CERTIFICATION_REQUEST_STANDARD("PKCS #10 - Certification Request Standard", "application/pkcs10", ".p10"),
    PKCS_12_PERSONAL_INFORMATION_EXCHANGE_SYNTAX_STANDARD("PKCS #12 - Personal Information Exchange Syntax Standard", "application/x-pkcs12", ".p12"),
    PKCS_7_CRYPTOGRAPHIC_MESSAGE_SYNTAX_STANDARD_P7M("PKCS #7 - Cryptographic Message Syntax Standard", "application/pkcs7-mime", ".p7m"),
    PKCS_7_CRYPTOGRAPHIC_MESSAGE_SYNTAX_STANDARD_P7S("PKCS #7 - Cryptographic Message Syntax Standard", "application/pkcs7-signature", ".p7s"),
    PKCS_7_CRYPTOGRAPHIC_MESSAGE_SYNTAX_STANDARD_CERTIFICATE_REQUEST_RESPONSE("PKCS #7 - Cryptographic Message Syntax Standard (Certificate Request Response)", "application/x-pkcs7-certreqresp", ".p7r"),
    PKCS_7_CRYPTOGRAPHIC_MESSAGE_SYNTAX_STANDARD_CERTIFICATES("PKCS #7 - Cryptographic Message Syntax Standard (Certificates)", "application/x-pkcs7-certificates", ".p7b"),
    PKCS_8_PRIVATE_KEY_INFORMATION_SYNTAX_STANDARD("PKCS #8 - Private-Key Information Syntax Standard", "application/pkcs8", ".p8"),
    POCKETLEARN_VIEWERS("PocketLearn Viewers", "application/vnd.pocketlearn", ".plf"),
    PORTABLE_ANYMAP_IMAGE("Portable Anymap Image", "image/x-portable-anymap", ".pnm"),
    PORTABLE_BITMAP_FORMAT("Portable Bitmap Format", "image/x-portable-bitmap", ".pbm"),
    PORTABLE_COMPILED_FORMAT("Portable Compiled Format", "application/x-font-pcf", ".pcf"),
    PORTABLE_FONT_RESOURCE("Portable Font Resource", "application/font-tdpfr", ".pfr"),
    PORTABLE_GAME_NOTATION_CHESS_GAMES("Portable Game Notation (Chess Games)", "application/x-chess-pgn", ".pgn"),
    PORTABLE_GRAYMAP_FORMAT("Portable Graymap Format", "image/x-portable-graymap", ".pgm"),
    PORTABLE_NETWORK_GRAPHICS_PNG("Portable Network Graphics (PNG)", "image/png", ".png"),
    PORTABLE_NETWORK_GRAPHICS_PNG_CITRIX_CLIENT("Portable Network Graphics (PNG) (Citrix client)", "image/x-citrix-png", ".png"),
    PORTABLE_NETWORK_GRAPHICS_PNG_X_TOKEN("Portable Network Graphics (PNG) (x-token)", "image/x-png", ".png"),
    PORTABLE_PIXMAP_FORMAT("Portable Pixmap Format", "image/x-portable-pixmap", ".ppm"),
    PORTABLE_SYMMETRIC_KEY_CONTAINER("Portable Symmetric Key Container", "application/pskc+xml", ".pskcxml"),
    POSML("PosML", "application/vnd.ctc-posml", ".pml"),
    POSTSCRIPT("PostScript", "application/postscript", ".ai"),
    POSTSCRIPT_FONTS("PostScript Fonts", "application/x-font-type1", ".pfa"),
    POWERBUILDER("PowerBuilder", "application/vnd.powerbuilder6", ".pbd"),
    PRETTY_GOOD_PRIVACY("Pretty Good Privacy", "application/pgp-encrypted", ".pgp"),
    PRETTY_GOOD_PRIVACY_SIGNATURE("Pretty Good Privacy - Signature", "application/pgp-signature", ".pgp"),
    PREVIEW_SYSTEMS_ZIPLOCK_VBOX("Preview Systems ZipLock/VBox", "application/vnd.previewsystems.box", ".box"),
    PRINCETON_VIDEO_IMAGE("Princeton Video Image", "application/vnd.pvi.ptid1", ".ptid"),
    PRONUNCIATION_LEXICON_SPECIFICATION("Pronunciation Lexicon Specification", "application/pls+xml", ".pls"),
    PROPRIETARY_P_G_STANDARD_REPORTING_SYSTEM_STR("Proprietary P&G Standard Reporting System", "application/vnd.pg.format", ".str"),
    PROPRIETARY_P_G_STANDARD_REPORTING_SYSTEM_EI6("Proprietary P&G Standard Reporting System", "application/vnd.pg.osasli", ".ei6"),
    PRS_LINES_TAG("PRS Lines Tag", "text/prs.lines.tag", ".dsc"),
    PSF_FONTS("PSF Fonts", "application/x-font-linux-psf", ".psf"),
    PUBLISHARE_OBJECTS("PubliShare Objects", "application/vnd.publishare-delta-tree", ".qps"),
    QUALCOMMS_PLAZA_MOBILE_INTERNET("Qualcomm's Plaza Mobile Internet", "application/vnd.pmi.widget", ".wg"),
    QUARKXPRESS("QuarkXpress", "application/vnd.quark.quarkxpress", ".qxd"),
    QUASS_STREAM_PLAYER_ESF("QUASS Stream Player", "application/vnd.epson.esf", ".esf"),
    QUASS_STREAM_PLAYER_MSF("QUASS Stream Player", "application/vnd.epson.msf", ".msf"),
    QUASS_STREAM_PLAYER_SSF("QUASS Stream Player", "application/vnd.epson.ssf", ".ssf"),
    QUICKANIME_PLAYER("QuickAnime Player", "application/vnd.epson.quickanime", ".qam"),
    QUICKEN("Quicken", "application/vnd.intu.qfx", ".qfx"),
    QUICKTIME_VIDEO("Quicktime Video", "video/quicktime", ".qt"),
    RAR_ARCHIVE("RAR Archive", "application/x-rar-compressed", ".rar"),
    REAL_AUDIO_SOUND_RAM("Real Audio Sound", "audio/x-pn-realaudio", ".ram"),
    REAL_AUDIO_SOUND_RMP("Real Audio Sound", "audio/x-pn-realaudio-plugin", ".rmp"),
    REALLY_SIMPLE_DISCOVERY("Really Simple Discovery", "application/rsd+xml", ".rsd"),
    REALMEDIA("RealMedia", "application/vnd.rn-realmedia", ".rm"),
    REALVNC("RealVNC", "application/vnd.realvnc.bed", ".bed"),
    RECORDARE_APPLICATIONS_MXL("Recordare Applications", "application/vnd.recordare.musicxml", ".mxl"),
    RECORDARE_APPLICATIONS_MUSICXML("Recordare Applications", "application/vnd.recordare.musicxml+xml", ".musicxml"),
    RELAX_NG_COMPACT_SYNTAX("Relax NG Compact Syntax", "application/relax-ng-compact-syntax", ".rnc"),
    REMOTEDOCS_R_VIEWER("RemoteDocs R-Viewer", "application/vnd.data-vision.rdz", ".rdz"),
    RESOURCE_DESCRIPTION_FRAMEWORK("Resource Description Framework", "application/rdf+xml", ".rdf"),
    RETROPLATFORM_PLAYER("RetroPlatform Player", "application/vnd.cloanto.rp9", ".rp9"),
    RHYMBOX("RhymBox", "application/vnd.jisp", ".jisp"),
    RICH_TEXT_FORMAT("Rich Text Format", "application/rtf", ".rtf"),
    RICH_TEXT_FORMAT_RTF("Rich Text Format (RTF)", "text/richtext", ".rtx"),
    ROUTE_66_LOCATION_BASED_SERVICES("ROUTE 66 Location Based Services", "application/vnd.route66.link66+xml", ".link66"),
    RSS_REALLY_SIMPLE_SYNDICATION_RSS("RSS - Really Simple Syndication", "application/rss+xml", ".rss"),
    RSS_REALLY_SIMPLE_SYNDICATION_XML("RSS - Really Simple Syndication", "application/rss+xml", ".xml"),
    S_HEXDUMP_FORMAT("S Hexdump Format", "application/shf+xml", ".shf"),
    SAILINGTRACKER("SailingTracker", "application/vnd.sailingtracker.track", ".st"),
    SCALABLE_VECTOR_GRAPHICS_SVG("Scalable Vector Graphics (SVG)", "image/svg+xml", ".svg"),
    SCHEDULEUS("ScheduleUs", "application/vnd.sus-calendar", ".sus"),
    SEARCH_RETRIEVE_VIA_URL_RESPONSE_FORMAT("Search/Retrieve via URL Response Format", "application/sru+xml", ".sru"),
    SECURE_ELECTRONIC_TRANSACTION_PAYMENT("Secure Electronic Transaction - Payment", "application/set-payment-initiation", ".setpay"),
    SECURE_ELECTRONIC_TRANSACTION_REGISTRATION("Secure Electronic Transaction - Registration", "application/set-registration-initiation", ".setreg"),
    SECURED_EMAIL_SEMA("Secured eMail", "application/vnd.sema", ".sema"),
    SECURED_EMAIL_SEMD("Secured eMail", "application/vnd.semd", ".semd"),
    SECURED_EMAIL_SEMF("Secured eMail", "application/vnd.semf", ".semf"),
    SEEMAIL("SeeMail", "application/vnd.seemail", ".see"),
    SERVER_NORMAL_FORMAT("Server Normal Format", "application/x-font-snf", ".snf"),
    SERVER_BASED_CERTIFICATE_VALIDATION_PROTOCOL_VALIDATION_POLICIES_REQUEST("Server-Based Certificate Validation Protocol - Validation Policies - Request", "application/scvp-vp-request", ".spq"),
    SERVER_BASED_CERTIFICATE_VALIDATION_PROTOCOL_VALIDATION_POLICIES_RESPONSE("Server-Based Certificate Validation Protocol - Validation Policies - Response", "application/scvp-vp-response", ".spp"),
    SERVER_BASED_CERTIFICATE_VALIDATION_PROTOCOL_VALIDATION_REQUEST("Server-Based Certificate Validation Protocol - Validation Request", "application/scvp-cv-request", ".scq"),
    SERVER_BASED_CERTIFICATE_VALIDATION_PROTOCOL_VALIDATION_RESPONSE("Server-Based Certificate Validation Protocol - Validation Response", "application/scvp-cv-response", ".scs"),
    SESSION_DESCRIPTION_PROTOCOL("Session Description Protocol", "application/sdp", ".sdp"),
    SETEXT("Setext", "text/x-setext", ".etx"),
    SGI_MOVIE("SGI Movie", "video/x-sgi-movie", ".movie"),
    SHANA_INFORMED_FILLER_IFM("Shana Informed Filler", "application/vnd.shana.informed.formdata", ".ifm"),
    SHANA_INFORMED_FILLER_ITP("Shana Informed Filler", "application/vnd.shana.informed.formtemplate", ".itp"),
    SHANA_INFORMED_FILLER_IIF("Shana Informed Filler", "application/vnd.shana.informed.interchange", ".iif"),
    SHANA_INFORMED_FILLER_IPK("Shana Informed Filler", "application/vnd.shana.informed.package", ".ipk"),
    SHARING_TRANSACTION_FRAUD_DATA("Sharing Transaction Fraud Data", "application/thraud+xml", ".tfi"),
    SHELL_ARCHIVE("Shell Archive", "application/x-shar", ".shar"),
    SILICON_GRAPHICS_RGB_BITMAP("Silicon Graphics RGB Bitmap", "image/x-rgb", ".rgb"),
    SIMPLEANIMELITE_PLAYER("SimpleAnimeLite Player", "application/vnd.epson.salt", ".slt"),
    SIMPLY_ACCOUNTING("Simply Accounting", "application/vnd.accpac.simply.aso", ".aso"),
    SIMPLY_ACCOUNTING_DATA_IMPORT("Simply Accounting - Data Import", "application/vnd.accpac.simply.imp", ".imp"),
    SIMTECH_MINDMAPPER("SimTech MindMapper", "application/vnd.simtech-mindmapper", ".twd"),
    SIXTH_FLOOR_MEDIA_COMMONSPACE("Sixth Floor Media - CommonSpace", "application/vnd.commonspace", ".csp"),
    SMAF_AUDIO("SMAF Audio", "application/vnd.yamaha.smaf-audio", ".saf"),
    SMAF_FILE("SMAF File", "application/vnd.smaf", ".mmf"),
    SMAF_PHRASE("SMAF Phrase", "application/vnd.yamaha.smaf-phrase", ".spf"),
    SMART_TECHNOLOGIES_APPS("SMART Technologies Apps", "application/vnd.smart.teacher", ".teacher"),
    SOURCEVIEW_DOCUMENT("SourceView Document", "application/vnd.svd", ".svd"),
    SPARQL_QUERY("SPARQL - Query", "application/sparql-query", ".rq"),
    SPARQL_RESULTS("SPARQL - Results", "application/sparql-results+xml", ".srx"),
    SPEECH_RECOGNITION_GRAMMAR_SPECIFICATION("Speech Recognition Grammar Specification", "application/srgs", ".gram"),
    SPEECH_RECOGNITION_GRAMMAR_SPECIFICATION_XML("Speech Recognition Grammar Specification - XML", "application/srgs+xml", ".grxml"),
    SPEECH_SYNTHESIS_MARKUP_LANGUAGE("Speech Synthesis Markup Language", "application/ssml+xml", ".ssml"),
    SSEYO_KOAN_PLAY_FILE("SSEYO Koan Play File", "application/vnd.koan", ".skp"),
    STANDARD_GENERALIZED_MARKUP_LANGUAGE_SGML("Standard Generalized Markup Language (SGML)", "text/sgml", ".sgml"),
    STAROFFICE_CALC("StarOffice - Calc", "application/vnd.stardivision.calc", ".sdc"),
    STAROFFICE_DRAW("StarOffice - Draw", "application/vnd.stardivision.draw", ".sda"),
    STAROFFICE_IMPRESS("StarOffice - Impress", "application/vnd.stardivision.impress", ".sdd"),
    STAROFFICE_MATH("StarOffice - Math", "application/vnd.stardivision.math", ".smf"),
    STAROFFICE_WRITER("StarOffice - Writer", "application/vnd.stardivision.writer", ".sdw"),
    STAROFFICE_WRITER_GLOBAL("StarOffice - Writer (Global)", "application/vnd.stardivision.writer-global", ".sgl"),
    STEPMANIA("StepMania", "application/vnd.stepmania.stepchart", ".sm"),
    STUFFIT_ARCHIVE_SIT("Stuffit Archive", "application/x-stuffit", ".sit"),
    STUFFIT_ARCHIVE_SITX("Stuffit Archive", "application/x-stuffitx", ".sitx"),
    SUDOKUMAGIC("SudokuMagic", "application/vnd.solent.sdkm+xml", ".sdkm"),
    SUGAR_LINUX_APPLICATION_BUNDLE("Sugar Linux Application Bundle", "application/vnd.olpc-sugar", ".xo"),
    SUN_AUDIO_AU_FILE_FORMAT("Sun Audio - Au file format", "audio/basic", ".au"),
    SUNDAHUS_WQ("SundaHus WQ", "application/vnd.wqd", ".wqd"),
    SYMBIAN_INSTALL_PACKAGE("Symbian Install Package", "application/vnd.symbian.install", ".sis"),
    SYNCHRONIZED_MULTIMEDIA_INTEGRATION_LANGUAGE("Synchronized Multimedia Integration Language", "application/smil+xml", ".smi"),
    SYNCML("SyncML", "application/vnd.syncml+xml", ".xsm"),
    SYNCML_DEVICE_MANAGEMENT_BDM("SyncML - Device Management", "application/vnd.syncml.dm+wbxml", ".bdm"),
    SYNCML_DEVICE_MANAGEMENT_XDM("SyncML - Device Management", "application/vnd.syncml.dm+xml", ".xdm"),
    SYSTEM_V_RELEASE_4_CPIO_ARCHIVE("System V Release 4 CPIO Archive", "application/x-sv4cpio", ".sv4cpio"),
    SYSTEM_V_RELEASE_4_CPIO_CHECKSUM_DATA("System V Release 4 CPIO Checksum Data", "application/x-sv4crc", ".sv4crc"),
    SYSTEMS_BIOLOGY_MARKUP_LANGUAGE("Systems Biology Markup Language", "application/sbml+xml", ".sbml"),
    TAB_SEPERATED_VALUES("Tab Seperated Values", "text/tab-separated-values", ".tsv"),
    TAGGED_IMAGE_FILE_FORMAT("Tagged Image File Format", "image/tiff", ".tiff"),
    TAO_INTENT("Tao Intent", "application/vnd.tao.intent-module-archive", ".tao"),
    TAR_FILE_TAPE_ARCHIVE("Tar File (Tape Archive)", "application/x-tar", ".tar"),
    TCL_SCRIPT("Tcl Script", "application/x-tcl", ".tcl"),
    TEX("TeX", "application/x-tex", ".tex"),
    TEX_FONT_METRIC("TeX Font Metric", "application/x-tex-tfm", ".tfm"),
    TEXT_ENCODING_AND_INTERCHANGE("Text Encoding and Interchange", "application/tei+xml", ".tei"),
    TEXT_FILE("Text File", "text/plain", ".txt"),
    TIBCO_SPOTFIRE_DXP("TIBCO Spotfire", "application/vnd.spotfire.dxp", ".dxp"),
    TIBCO_SPOTFIRE_SFS("TIBCO Spotfire", "application/vnd.spotfire.sfs", ".sfs"),
    TIME_STAMPED_DATA_ENVELOPE("Time Stamped Data Envelope", "application/timestamped-data", ".tsd"),
    TRI_SYSTEMS_CONFIG("TRI Systems Config", "application/vnd.trid.tpt", ".tpt"),
    TRISCAPE_MAP_EXPLORER("Triscape Map Explorer", "application/vnd.triscape.mxs", ".mxs"),
    TROFF("troff", "text/troff", ".t"),
    TRUE_BASIC("True BASIC", "application/vnd.trueapp", ".tra"),
    TRUETYPE_FONT("TrueType Font", "application/x-font-ttf", ".ttf"),
    TURTLE_TERSE_RDF_TRIPLE_LANGUAGE("Turtle (Terse RDF Triple Language)", "text/turtle", ".ttl"),
    UMAJIN("UMAJIN", "application/vnd.umajin", ".umj"),
    UNIQUE_OBJECT_MARKUP_LANGUAGE("Unique Object Markup Language", "application/vnd.uoml+xml", ".uoml"),
    UNITY_3D("Unity 3d", "application/vnd.unity", ".unityweb"),
    UNIVERSAL_FORMS_DESCRIPTION_LANGUAGE("Universal Forms Description Language", "application/vnd.ufdl", ".ufd"),
    URI_RESOLUTION_SERVICES("URI Resolution Services", "text/uri-list", ".uri"),
    USER_INTERFACE_QUARTZ_THEME_SYMBIAN("User Interface Quartz - Theme (Symbian)", "application/vnd.uiq.theme", ".utz"),
    USTAR_UNIFORM_STANDARD_TAPE_ARCHIVE("Ustar (Uniform Standard Tape Archive)", "application/x-ustar", ".ustar"),
    UUENCODE("UUEncode", "text/x-uuencode", ".uu"),
    VCALENDAR("vCalendar", "text/x-vcalendar", ".vcs"),
    VCARD("vCard", "text/x-vcard", ".vcf"),
    VIDEO_CD("Video CD", "application/x-cdlink", ".vcd"),
    VIEWPORT("Viewport+", "application/vnd.vsf", ".vsf"),
    VIRTUAL_REALITY_MODELING_LANGUAGE("Virtual Reality Modeling Language", "model/vrml", ".wrl"),
    VIRTUALCATALOG("VirtualCatalog", "application/vnd.vcx", ".vcx"),
    VIRTUE_MTS("Virtue MTS", "model/vnd.mts", ".mts"),
    VIRTUE_VTU("Virtue VTU", "model/vnd.vtu", ".vtu"),
    VISIONARY("Visionary", "application/vnd.visionary", ".vis"),
    VIVO("Vivo", "video/vnd.vivo", ".viv"),
    VOICE_BROWSER_CALL_CONTROL("Voice Browser Call Control", "application/ccxml+xml,", ".ccxml"),
    VOICEXML("VoiceXML", "application/voicexml+xml", ".vxml"),
    WAIS_SOURCE("WAIS Source", "application/x-wais-source", ".src"),
    WAP_BINARY_XML__WBXML("WAP Binary XML (WBXML)", "application/vnd.wap.wbxml", ".wbxml"),
    WAP_BITAMP_WBMP("WAP Bitamp (WBMP)", "image/vnd.wap.wbmp", ".wbmp"),
    WAVEFORM_AUDIO_FILE_FORMAT_WAV("Waveform Audio File Format (WAV)", "audio/x-wav", ".wav"),
    WEB_DISTRIBUTED_AUTHORING_AND_VERSIONING("Web Distributed Authoring and Versioning", "application/davmount+xml", ".davmount"),
    WEB_OPEN_FONT_FORMAT("Web Open Font Format", "application/x-font-woff", ".woff"),
    WEB_SERVICES_POLICY("Web Services Policy", "application/wspolicy+xml", ".wspolicy"),
    WEBP_IMAGE("WebP Image", "image/webp", ".webp"),
    WEBTURBO("WebTurbo", "application/vnd.webturbo", ".wtb"),
    WIDGET_PACKAGING_AND_XML_CONFIGURATION("Widget Packaging and XML Configuration", "application/widget", ".wgt"),
    WINHELP("WinHelp", "application/winhlp", ".hlp"),
    WIRELESS_MARKUP_LANGUAGE_WML("Wireless Markup Language (WML)", "text/vnd.wap.wml", ".wml"),
    WIRELESS_MARKUP_LANGUAGE_SCRIPT_WMLSCRIPT("Wireless Markup Language Script (WMLScript)", "text/vnd.wap.wmlscript", ".wmls"),
    WMLSCRIPT("WMLScript", "application/vnd.wap.wmlscriptc", ".wmlsc"),
    WORDPERFECT("Wordperfect", "application/vnd.wordperfect", ".wpd"),
    WORLDTALK("Worldtalk", "application/vnd.wt.stf", ".stf"),
    WSDL_WEB_SERVICES_DESCRIPTION_LANGUAGE("WSDL - Web Services Description Language", "application/wsdl+xml", ".wsdl"),
    X_BITMAP("X BitMap", "image/x-xbitmap", ".xbm"),
    X_PIXMAP("X PixMap", "image/x-xpixmap", ".xpm"),
    X_WINDOW_DUMP("X Window Dump", "image/x-xwindowdump", ".xwd"),
    X_509_CERTIFICATE("X.509 Certificate", "application/x-x509-ca-cert", ".der"),
    XFIG("Xfig", "application/x-xfig", ".fig"),
    XHTML_THE_EXTENSIBLE_HYPERTEXT_MARKUP_LANGUAGE("XHTML - The Extensible HyperText Markup Language", "application/xhtml+xml", ".xhtml"),
    XML_EXTENSIBLE_MARKUP_LANGUAGE("XML - Extensible Markup Language", "application/xml", ".xml"),
    XML_CONFIGURATION_ACCESS_PROTOCOL_XCAP_DIFF("XML Configuration Access Protocol - XCAP Diff", "application/xcap-diff+xml", ".xdf"),
    XML_ENCRYPTION_SYNTAX_AND_PROCESSING("XML Encryption Syntax and Processing", "application/xenc+xml", ".xenc"),
    XML_PATCH_FRAMEWORK("XML Patch Framework", "application/patch-ops-error+xml", ".xer"),
    XML_RESOURCE_LISTS_RL("XML Resource Lists", "application/resource-lists+xml", ".rl"),
    XML_RESOURCE_LISTS_RS("XML Resource Lists", "application/rls-services+xml", ".rs"),
    XML_RESOURCE_LISTS_DIFF("XML Resource Lists Diff", "application/resource-lists-diff+xml", ".rld"),
    XML_TRANSFORMATIONS("XML Transformations", "application/xslt+xml", ".xslt"),
    XML_BINARY_OPTIMIZED_PACKAGING("XML-Binary Optimized Packaging", "application/xop+xml", ".xop"),
    XPINSTALL_MOZILLA("XPInstall - Mozilla", "application/x-xpinstall", ".xpi"),
    XSPF_XML_SHAREABLE_PLAYLIST_FORMAT("XSPF - XML Shareable Playlist Format", "application/xspf+xml", ".xspf"),
    XUL_XML_USER_INTERFACE_LANGUAGE("XUL - XML User Interface Language", "application/vnd.mozilla.xul+xml", ".xul"),
    XYZ_FILE_FORMAT("XYZ File Format", "chemical/x-xyz", ".xyz"),
    YAML_AINT_MARKUP_LANGUAGE_YET_ANOTHER_MARKUP_LANGUAGE("YAML Ain't Markup Language / Yet Another Markup Language", "text/yaml", ".yaml"),
    YANG_DATA_MODELING_LANGUAGE("YANG Data Modeling Language", "application/yang", ".yang"),
    YIN_YANG_XML("YIN (YANG - XML)", "application/yin+xml", ".yin"),
    Z_U_L_GEOMETRY("Z.U.L. Geometry", "application/vnd.zul", ".zir"),
    ZIP_ARCHIVE("Zip Archive", "application/zip", ".zip"),
    ZVUE_MEDIA_MANAGER("ZVUE Media Manager", "application/vnd.handheld-entertainment+xml", ".zmm"),
    ZZAZZ_DECK("Zzazz Deck", "application/vnd.zzazz.deck+xml", ".zaz"),

    WEB_OPEN_FONT_FORMAT_2("Web Open Font Format 2", "application/x-font-woff2", ".woff2"),
    SFNT_FONT_FILE("OpenType Font File", "application/font-sfnt", ".sfnt");

    private final String mName;
    private final String mType;
    private final String mExtension;

    MediaTypes(String name, String type, String extension) {
        this.mName = name;
        this.mType = type;
        this.mExtension = extension;
    }

    public static MediaTypes[] getAllMediaTypesForExtension(String extension) {
        if (extension == null) {
            throw new IllegalArgumentException("extension");
        }
        List<MediaTypes> mediaTypes = new ArrayList<>();
        for (MediaTypes mediaType : MediaTypes.values()) {
            if (extension.equals(mediaType.mExtension)) {
                mediaTypes.add(mediaType);
            }
        }
        return mediaTypes.toArray(new MediaTypes[0]);
    }

    public static String[] getAllExtensionsForMediaType(String mediaType) {
        if (mediaType == null) {
            throw new IllegalArgumentException("mediaType");
        }
        List<String> mediaTypes = new ArrayList<>();
        for (MediaTypes mediaTypeObj : MediaTypes.values()) {
            if (mediaType.equals(mediaTypeObj.mType)) {
                mediaTypes.add(mediaTypeObj.mExtension);
            }
        }
        return mediaTypes.toArray(new String[0]);
    }

    public static String detectMediaTypeForWeb(String extension) {
        if (extension == null) {
            throw new IllegalArgumentException("extension");
        }
        final List<MediaTypes> mediaTypes = new ArrayList<>(Arrays.asList(MediaTypes.values()));
        mediaTypes.remove(MediaTypes.ATOM_SYNDICATION_FORMAT_XML);
        mediaTypes.remove(MediaTypes.RSS_REALLY_SIMPLE_SYNDICATION_XML);
        mediaTypes.remove(MediaTypes.JPG_IMAGE_CITRIX_CLIENT);
        mediaTypes.remove(MediaTypes.JPEG_IMAGE_CITRIX_CLIENT);
        mediaTypes.remove(MediaTypes.PORTABLE_NETWORK_GRAPHICS_PNG_X_TOKEN);
        mediaTypes.remove(MediaTypes.PORTABLE_NETWORK_GRAPHICS_PNG_CITRIX_CLIENT);
        for (MediaTypes mediaType : mediaTypes) {
            if (extension.equals(mediaType.mExtension)) {
                return mediaType.mType;
            }
        }
        return BINARY_DATA.mType;
    }

    public String getName() {
        return mName;
    }

    public String getType() {
        return mType;
    }

    public String getExtension() {
        return mExtension;
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this)
                .append("\n\tName", mName)
                .append(", Type", mType)
                .append(", Extension", mExtension)
                .append("\n").toString();
    }
}
