# Build the project
FROM maven:3-eclipse-temurin-8 as builder
COPY pom.xml /usr/local/build/pom.xml
COPY src /usr/local/build/src/
WORKDIR /usr/local/build
RUN mvn clean package -DskipTests

# Configure Docker Image
FROM eclipse-temurin:8-jre-jammy

RUN apt-get update && \
    echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | debconf-set-selections && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        fontconfig software-properties-common && \
    apt-add-repository multiverse && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        ttf-mscorefonts-installer && \
    fc-cache -f && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p /home/groupdocs/app && \
    mkdir -p /home/groupdocs/app/DocumentSamples && \
    mkdir -p /home/groupdocs/app/Licenses
COPY /DocumentSamples /home/groupdocs/app/DocumentSamples
COPY /configuration.yml /home/groupdocs/app/configuration.yml
COPY --from=builder /usr/local/build/target/viewer-dropwizard-*.jar /home/groupdocs/app/app.jar
WORKDIR /home/groupdocs/app

ENV LIC_PATH "Licenses"
ENV DOWNLOAD_ON true
ENV UPLOAD_ON true
ENV PRINT_ON true
ENV BROWSE_ON true
ENV RIGHTCLICK_ON false
ENV FILES_DIR "DocumentSamples"
ENV HOST_ADDRESS ""

LABEL version="25.2" \
      maintainer="GroupDocs Team" \
      url="https://products.groupdocs.com/viewer/java" \
      documentation="https://docs.groupdocs.com/viewer/java" \
      source="https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-Java" \
      description="GroupDocs.Viewer for Java Dropwizard sample, based on Debian Bullseye and OpenJDK 8"

EXPOSE 8080

VOLUME [ "/home/groupdocs/app", "/home/groupdocs/app/DocumentSamples", "/home/groupdocs/app/Licenses" ]

ENTRYPOINT [ "java", "-jar", "app.jar", "configuration.yml" ]